networks:
  default:
    driver: bridge
    name: roboshop
    external: true

services:
  mongodb:
    container_name: mongodb
    image: gautamjames/mongodb:v3

  catalogue:
     container_name: catalogue
     image: gautamjames/catalogue:v3
     depends_on:
     - mongodb

  redis:
    container_name: redis
    image: redis:7.0

  user:
    conatainer_name: user
    image: gautamjames/user:v3
    depends_on:
    - redis
    - mongodb

  cart:
    container_name: cart
    image: gautamjames/cart:v3
    depends_on:
    - catalogue
    - redis

  mysql:
    container_name: mysql
    image: gautamjames/mysql:v3

  shipping:
    container_name: shipping
    image: gautamjames/shipping:v3
    depends_on:
    - mysql
    - cart



