networks:
  default:
    driver: bridge
    name: roboshop
    external: true

services:
  mongodb:
    container_name: mongodb
    image: gautamjames/mongodb:v3

  catalogue:
     container_name: catalogue
     image: gautamjames/catalogue:v3
     depends_on:
     - mongodb

  redis:
    container_name: redis
    image: redis:7.0

  user:
    container_name: user
    image: gautamjames/user:v3
    depends_on:
    - redis
    - mongodb

  cart:
    container_name: cart
    image: gautamjames/cart:v3
    depends_on:
    - catalogue
    - redis

  mysql:
    container_name: mysql
    image: gautamjames/mysql:v3

  shipping:
    container_name: shipping
    image: gautamjames/shipping:v3
    depends_on:
    - mysql
    - cart

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123

